spring.datasource.url=jdbc:postgresql://localhost:5433/ingressify
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
